title: "Digital Spark HQ"
description: "SEO, web design, and digital marketing services for UK and global brands."
baseurl: "" 
url: "https://digitalsparkhq.com"

permalink: /:title/

plugins:
  - jekyll-sitemap
